Repository TEAM-SEONYAK/SEONYAK_CLIENT, pull requests merged in 2024-10, with the labels that each got.

#253 [ Fix/#249 ] 선배 nav바 둘러보기 탭 클릭 막기, promiseList 페이지 콘솔에 key값 중복 에러 나는 거 해결
  src/components/commons/Nav.tsx
  src/pages/promiseList/components/PromiseTap.tsx
Labels: 🛠 Fix, 서진, size/s

#252 [ Fix/#248 ] personal Topic (직접작성) 일 경우 컴포넌트 안 뜨는 이슈
  src/Router.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
  src/pages/promiseList/components/ProfileContainer.tsx
Labels: 🛠 Fix, 서진, size/xs

#243 [ Fix ] 구글밋 입장 API 재연결, 입장시간 렌더링 전 - 추가
  src/hooks/useCountDown.ts
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/promiseList/components/PromiseTap.tsx
  src/pages/promiseList/components/PromiseTimerBtn.tsx
  src/pages/promiseList/components/RecentCard.tsx
Labels: 🛠 Fix, 서진, size/m

#264 [ Fix ] junior promise 렌더링 에러 해결
  src/pages/juniorPromise/JuniorPromisePage.tsx
Labels: 🛠 Fix, 지은, 예림, size/m

#258 [ Fix ] navigate 오류 수정 2
  src/pages/onboarding/components/Layout.tsx
  src/pages/onboarding/components/commonOnboarding/Step계열선택.tsx
  src/pages/onboarding/components/juniorOnboarding/Step이메일입력.tsx
  src/pages/onboarding/juniorOnboarding/apis/.gitkeep
  src/pages/onboarding/juniorOnboarding/components/.gitkeep
  src/pages/onboarding/juniorOnboarding/constants/.gitkeep
  src/pages/onboarding/juniorOnboarding/types/.gitkeep
  src/pages/onboarding/juniorOnboarding/utils/.gitkeep
  src/pages/onboarding/seniorOnboarding/apis/.gitkeep
  src/pages/onboarding/seniorOnboarding/components/.gitkeep
  src/pages/onboarding/seniorOnboarding/types/.gitkeep
  src/pages/onboarding/seniorOnboarding/utils/.gitkeep
Labels: size/s

#251 [ Fix ] 닉네임 중복체크 재검사 시 초기화 & 409에러 중복처리
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
  src/pages/onboarding/hooks/useNicknameQuery.ts
Labels: 🛠 Fix, 숭, size/s

#257 [ Fix ] navigate 오류 수정 1
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx
Labels: size/s

#266 [ Refactor ] junior propmise page isBottomSheetOpen프롭스 제거
  src/components/commons/ToggleButton.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/BottomSheet.tsx
Labels: ♻️ Refactor, 예림, size/m

#269 [ Fix ] 약속리스트 변경된 라우터 반영 / 이전탭 남아있도록 수정
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/promiseList/components/PromiseTap.tsx
Labels: 🛠 Fix, 서진, size/s

#278 [ Design ] 후배 약속신청 텍스트박스 글씨 조정
  src/pages/juniorPromiseRequest/components/WorryTextarea.tsx
Labels: 💄 Design, 지은, size/xs

#270 [ Fix ] 약속리스트 페이지 레이아웃 조정 / 선배 상세정보(Preview 컴포넌트) 회사 색상 깜빡이는 이슈 수정
  src/App.tsx
  src/components/commons/Header.tsx
  src/components/commons/seniorCard/SeniorCard.tsx
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
Labels: 🛠 Fix, 서진, size/s

#286 [ Design ] 후배 약속신청 확인 모달 위치 수정
  src/pages/juniorPromiseRequest/components/RequestComplete.tsx
Labels: 🛠 Fix, 💄 Design, 지은

#281 [ Fix ] 온보딩 중 새로고침 시 1단계로 navigate
  src/pages/onboarding/components/Layout.tsx
Labels: size/xs

#274 [ Fix ] 약속신청 사유 하나만 가도록 수정
  src/pages/juniorPromiseRequest/JuniorPromiseRequestPage.tsx
Labels: 🛠 Fix, 지은, size/xs

#276 [ Fix ] 빈 문자열로 약속신청 하는 경우 막기
  src/pages/juniorPromiseRequest/JuniorPromiseRequestPage.tsx
  src/pages/juniorPromiseRequest/components/WorryButtons.tsx
  src/pages/juniorPromiseRequest/components/WorryTextarea.tsx
Labels: 🛠 Fix, 지은, size/s

#288 [ Fix ] full 그래픽 반응형 적용
  src/assets/svgs/img_grad.svg
  src/assets/svgs/img_onboarding_hb.svg
  src/assets/svgs/img_onboarding_sb.svg
  src/assets/svgs/img_senior_refresh.svg
  src/assets/svgs/index.tsx
  src/pages/join/JoinPage.tsx
  src/pages/join/components/Welcome.tsx
  src/pages/login/SignupPage.tsx
  src/pages/seniorProfile/SeniorProfilePage.tsx
  src/pages/seniorProfile/components/Init.tsx
Labels: ✨ Feat, 🛠 Fix, 진, size/xl

#282 [ Fix ] 선배 약속 거절 페이지 에러 수정
  src/assets/svgs/ic_arrow_down_mg.svg
  src/components/commons/BottomSheet.tsx
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseList/PromiseListPage.tsx
  src/pages/promiseList/hooks/queries.ts
Labels: 🛠 Fix, 서진, size/m

#287 [ Fix ] 약속 리스트 페이지 에러 처리
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
  src/pages/promiseDetail/apis/postGoogleMeetLink.ts
  src/pages/promiseDetail/hooks/queries.ts
  src/pages/promiseList/PromiseListPage.tsx
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/promiseList/components/PromiseTap.tsx
  src/pages/promiseList/components/RecentCard.tsx
  src/pages/promiseList/hooks/queries.ts
Labels: 🛠 Fix, 서진, size/m

#290 [ Design ] 에러페이지 높이 크기 반영 , 가입페이지 배경 svg로 변경 반영
  src/assets/svgs/index.tsx
  src/assets/svgs/joinBgImg.svg
  src/assets/svgs/joinHbBgImg.svg
  src/assets/svgs/joinSbBgImg.svg
  src/pages/errorPage/ErrorPage.tsx
  src/pages/join/JoinPage.tsx
  src/pages/login/SignupPage.tsx
Labels: 💄 Design, 서진, size/m

#298 [ fix ] main PR : nav바 role 받아오는 로직 getRole 함수로 변경
  src/components/commons/Nav.tsx
Labels: 서진, 🔥 hotfix

#297 [ fix ] nav바 role 받아오는 로직 getRole 함수로 변경
  src/components/commons/Nav.tsx
Labels: 서진, size/xs, 🔥 hotfix

#295 [ Feat ] 온보딩, 선배프로필 등록 데이터 연결 및 디자인 QA 반영
  src/components/commons/seniorCard/SeniorCard.tsx
  src/pages/seniorProfile/SeniorProfilePage.tsx
  src/pages/seniorProfile/components/Example.tsx
  src/pages/seniorProfile/components/preView/Review.tsx
Labels: ✨ Feat, 진, size/s

#293 [ Fix ] Og태그 이미지 적용
  index.html
Labels: 🛠 Fix, size/xs

#315 [ Fix ] 후배 온보딩 완료 뷰 개선
  src/pages/onboarding/components/Layout.tsx
  src/pages/onboarding/components/juniorOnboarding/StepComplete.tsx
Labels: size/s

#323 [ Feat ] 명함 사진 Presigned URL 연결
  src/pages/onboarding/apis/businesscardAxios.ts
  src/pages/onboarding/apis/profileImageAxios.ts
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/components/seniorOnboarding/Step명함인증.tsx
  src/pages/onboarding/hooks/useBusinessCardQuery.ts
  src/pages/onboarding/hooks/usePresignedUrl.ts
Labels: ✨ Feat, 숭, size/m

#310 [ Fix ] 휴대폰에서 캘린더 바텀시트 밀리는 현상 해결
  src/pages/juniorPromiseRequest/components/CalendarBottomBar.tsx
  src/pages/juniorPromiseRequest/components/CalendarBottomSheet.tsx
Labels: 🛠 Fix, 💄 Design, 지은, size/s

#319 [ Fix ] 그래픽 사이즈 조정
  src/pages/seniorProfile/components/Init.tsx
Labels: 🛠 Fix, 진, size/xs
