Repository TEAM-SEONYAK/SEONYAK_CLIENT, pull requests merged in 2024-11, with the labels that each got.

#332 [ Fix ] 후배 학교 메일 인증 API 변경사항 반영
  src/pages/onboarding/apis/univAxios.ts
  src/pages/onboarding/components/juniorOnboarding/Step이메일입력.tsx
  src/pages/onboarding/hooks/useUnivQuery.ts
Labels: ✨ Feat, 숭, size/m

#333 [ Feat ] 로그인 관련 에러 처리 (존재하지 않는 회원일 경우, 토큰 만료)
  src/pages/login/hooks/useGoogleLoginMutation.ts
  src/utils/apis/index.ts
  src/utils/storage.ts
Labels: ✨ Feat, 숭, size/s

#322 [ Feat ] 에러페이지 변경사항 적용
  src/pages/errorPage/ErrorPage.tsx
Labels: ✨ Feat, size/m

#335 [ Fix ] 모바일뷰 캘린더 하단바 안가려지게 수정
  src/pages/juniorPromiseRequest/components/CalendarBottomSheet.tsx
Labels: 🛠 Fix, 지은, size/xs

#336 [ Fix ] 약속 리스트 후배일 경우 뒤로가기 탭 남아있도록 하기
  src/components/commons/Nav.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
  src/pages/promiseList/components/PromiseTap.tsx
Labels: 🛠 Fix, 서진, size/s

#339 [ Fix ] 선후배 Nav바 다른 거 반영
  src/components/commons/Nav.tsx
Labels: 🛠 Fix, 서진, size/s

#341 [ Fix ] 가입시 Role 받아오는 로직 수정
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/hooks/useJoinQuery.ts
  src/pages/promiseList/PromiseListPage.tsx
Labels: 🛠 Fix, 서진, size/xs

#344 [ Feat ] 닉네임 조건 체크 가시화
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
Labels: size/xs

#349 [ Fix ] 이미지 미업로드 시 빈문자열로 처리하도록 수정
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
  src/pages/onboarding/type.ts
Labels: size/xs

#346 [ Fix ] OG IMG 경로변경 -> 익스텐션으로 확인 완!
  index.html
  src/assets/favicon/favicon.svg
Labels: 🛠 Fix, 예림, size/xs

#352 [ Fix ] 에러페이지 홈으로 클릭시 이동 변경사항 반영
  src/pages/errorPage/ErrorPage.tsx
Labels: 🛠 Fix, 예림, size/s

#340 [ Fix ] junior promise page QA 반영
  src/components/commons/SeniorCard.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/BottomSheet.tsx
  src/pages/juniorPromise/components/FieldList.tsx
  src/pages/juniorPromise/components/PositionList.tsx
  src/pages/juniorPromise/components/SeniorSearch.tsx
  src/pages/juniorPromise/components/seniorFilter/Banner.tsx
Labels: 🛠 Fix, 예림, size/m

#353 [ Feat ] 타이머 종료되면 입력 필드 초기화
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
Labels: ✨ Feat, 지은, size/xs
