Repository TEAM-SEONYAK/SEONYAK_CLIENT, pull requests merged in 2024-07, with the labels that each got.

#1 [Init] eslint, prettier 초기세팅
  .eslintrc.cjs
  .eslintrc.json
  .prettierrc
  package.json
  yarn.lock
Labels: 🪡 Init, 지은

#3 [Init] stylelint 초기세팅
  .eslintrc.json
  .stylelintrc
  package.json
  yarn.lock
Labels: 🪡 Init, 예림

#5 [Init] PR Size Labeler
  .github/workflows/labeler.yml
Labels: 🪡 Init, 진

#7 🎉 [ Init ] PR, Issue Template 코드리뷰 반영
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.yml
  .github/ISSUE_TEMPLATE/♻️-refactor-template.md
  .github/ISSUE_TEMPLATE/🐛-bug-template.md
  .github/ISSUE_TEMPLATE/🚀-feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🪡 Init, 진, size/m

#10 [Init/#9] 디자인 시스템 초기세팅
  .eslintrc.json
  .stylelintrc
  index.html
  package.json
  src/App.tsx
  src/styles/.gitkeep
  src/styles/emotion.d.ts
  src/styles/globalStyle.ts
  src/styles/theme.ts
  yarn.lock
Labels: 🪡 Init, 서진, size/l

#14 [ Feat ] router 연결
  public/vite.svg
  src/App.tsx
  src/Router.tsx
  src/main.tsx
  src/pages/home/Home.tsx
  src/pages/home/apis/.gitkeep
  src/pages/home/components/.gitkeep
  src/pages/home/constants/.gitkeep
  src/pages/home/types/.gitkeep
  src/pages/home/utils/.gitkeep
  src/pages/juniorPromise/JuniorPromise.tsx
  src/pages/juniorPromise/apis/.gitkeep
  src/pages/juniorPromise/components/.gitkeep
  src/pages/juniorPromise/constants/.gitkeep
  src/pages/juniorPromise/types/.gitkeep
  src/pages/juniorPromise/utils/.gitkeep
  src/pages/main/Main.tsx
  src/pages/onboarding/juniorOnboarding/JuniorOnboarding.tsx
  src/pages/onboarding/juniorOnboarding/apis/.gitkeep
  src/pages/onboarding/juniorOnboarding/components/.gitkeep
  src/pages/onboarding/juniorOnboarding/constants/.gitkeep
  src/pages/onboarding/juniorOnboarding/types/.gitkeep
  src/pages/onboarding/juniorOnboarding/utils/.gitkeep
  src/pages/onboarding/seniorOnboarding/SeniorOnboarding.tsx
  src/pages/onboarding/seniorOnboarding/apis/.gitkeep
  src/pages/onboarding/seniorOnboarding/components/.gitkeep
  src/pages/onboarding/seniorOnboarding/constants/.gitkeep
  src/pages/onboarding/seniorOnboarding/types/.gitkeep
  src/pages/onboarding/seniorOnboarding/utils/.gitkeep
  src/pages/seniorProfile/SeniorProfile.tsx
  src/pages/seniorProfile/apis/.gitkeep
  src/pages/seniorProfile/components/.gitkeep
  src/pages/seniorProfile/constants/.gitkeep
  src/pages/seniorProfile/types/.gitkeep
  src/pages/seniorProfile/utils/.gitkeep
Labels: ✨ Feat, 진, size/m

#26 [ Design ] OnboardingPage 공통 TitleBox 컴포넌트 퍼블리싱
  src/pages/onboarding/components/TitleBox.tsx
  src/pages/onboarding/constants.ts
  src/pages/onboarding/seniorOnboarding/SeniorOnboardingPage.tsx
Labels: 💄 Design, 숭, size/m

#29 [ Design ] OnboardingPage 공통 InputBox 퍼블리싱
  src/pages/onboarding/components/TextBox.tsx
  src/pages/onboarding/seniorOnboarding/SeniorOnboardingPage.tsx
Labels: 💄 Design, 숭, size/m

#28 [ Feat ] 공통 컴포넌트 (버튼, input, 에러 메시지, 헤더, 프로그래스바) 퍼블리싱
  src/App.tsx
  src/assets/svgs/TempLogo.svg
  src/assets/svgs/ic_alarm.svg
  src/assets/svgs/ic_close.svg
  src/assets/svgs/icn_arrow_left.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/logo-alarm.svg
  src/components/commons/FullButton.tsx
  src/components/commons/Header.tsx
  src/components/commons/Textarea.tsx
  src/components/commons/WarnDescription.tsx
  src/custom.d.ts
Labels: ✨ Feat, 서진, size/m

#31 [ Design ] JuniorPromise 시간 선택 부분 퍼블리싱
  src/assets/svgs/ic_check.svg
  src/assets/svgs/index.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/TimeSelectionButton.tsx
  src/pages/juniorPromise/components/TimeSelectionTitleWrapper.tsx
  src/pages/juniorPromise/constants/constants.ts
Labels: 💄 Design, 지은, size/m

#37 [ Design ] OnboardingPage 공통 SearchBox 퍼블리싱
  src/assets/svgs/ic_cancel.svg
  src/assets/svgs/ic_search.svg
  src/assets/svgs/index.tsx
  src/pages/onboarding/components/SearchBox.tsx
  src/pages/onboarding/juniorOnboarding/JuniorOnboardingPage.tsx
Labels: 💄 Design, 숭, size/m

#40 [ Design ] OnboardingPage 공통 Layout 퍼블리싱
  src/components/commons/FullButton.tsx
  src/components/commons/Header.tsx
  src/components/commons/ProgressBar.tsx
  src/pages/onboarding/components/Layout.tsx
  src/pages/onboarding/juniorOnboarding/JuniorOnboardingPage.tsx
Labels: 💄 Design, 숭, size/m

#51 [ Setting ] login path route 추가
  src/Router.tsx
  src/pages/home/HomePage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/login/apis/loginAxios.ts
  src/pages/login/components/.gitkeep
  src/pages/login/hooks/useLoginQuery.ts
Labels: 🪡 Setting, 숭, size/s

#54 [ Setting ] alias 설정
  package.json
  src/pages/login/LoginPage.tsx
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 🪡 Setting, 숭, size/s

#55 [ Feat ] Onboarding 관련 폴더 구조 수정
  src/Router.tsx
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/onboarding/juniorOnboarding/JuniorOnboardingPage.tsx
  src/pages/onboarding/seniorOnboarding/SeniorOnboardingPage.tsx
  src/pages/onboarding/seniorOnboarding/constants/.gitkeep
Labels: ✨ Feat, 숭, size/m

#59 [ FIX ] toggle button 공통 컴포넌트 수정
  src/components/commons/ToggleButton.tsx
Labels: 🛠 Fix, 지은, size/s

#41 [Design]공통컴포넌트(선배프로필 리스트) 퍼블리싱
  src/components/commons/seniorCard/ SeniorCard.tsx
  src/components/commons/seniorCard/seniorCardConstants.ts
  src/components/commons/seniorCard/utils/ getLevelName.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: 💄 Design, 예림, size/l

#36 [ Feat ] 공통 모달 구현
  src/assets/svgs/ic_close.svg
  src/components/commons/modal/AutoCloseModal.tsx
  src/components/commons/modal/BtnModal.tsx
Labels: ✨ Feat, 서진, size/m

#44 [ Design ] 선/후배 약속 리스트 뷰 레이아웃
  src/Router.tsx
  src/assets/svgs/ic_navi_look_black.svg
  src/assets/svgs/ic_navi_look_gray.svg
  src/assets/svgs/ic_navi_my_black.svg
  src/assets/svgs/ic_navi_my_gray.svg
  src/assets/svgs/ic_navi_promise_black.svg
  src/assets/svgs/ic_navi_promise_gray.svg
  src/assets/svgs/index.tsx
  src/components/commons/Nav.tsx
  src/components/commons/seniorCard/SeniorCard.tsx
  src/components/commons/seniorCard/utils/getLevelName.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/promiseList/PromiseListPage.tsx
  src/pages/promiseList/commons/Layout.tsx
  src/pages/promiseList/commons/PromiseTap.tsx
  src/pages/promiseList/commons/Title.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: 💄 Design, 서진, size/m

#49 [Design] 선배 프로필리스트 감싸는 배경 구현
  src/assets/svgs/ArrowDownIc.svg
  src/assets/svgs/Line292Ic.svg
  src/assets/svgs/ResetIc.svg
  src/assets/svgs/index.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/FilterButton.tsx
  src/pages/juniorPromise/components/SeniorListBackground.tsx
Labels: 💄 Design, 예림

#75 [Design] 후배 약속잡는 플로우_선배 필터링 바텀시트
  src/assets/svgs/ReloadIc.svg
  src/assets/svgs/index.tsx
  src/components/commons/seniorCard/SeniorCard.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/.gitkeep
  src/pages/juniorPromise/components/BottomSheetBg.tsx
  src/pages/juniorPromise/components/FilterButton.tsx
  src/pages/juniorPromise/components/SeniorListBackground.tsx
Labels: 💄 Design, 예림, size/m

#62 [ Design ] 후배_약속 뷰 배너 퍼블리싱
  src/assets/svgs/index.tsx
  src/assets/svgs/tech_character.svg
  src/pages/juniorPromise/components/Banner.tsx
Labels: 💄 Design, 지은, size/m

#73 [ Design ] 후배_약속날짜 선택 캘린더 퍼블리싱
  .stylelintrc
  package.json
  src/pages/juniorPromise/components/CustomCalendar.tsx
  src/pages/juniorPromise/utils/getTomorrow.ts
  yarn.lock
Labels: 💄 Design, 지은, size/m

#91 [ Design ] JuniorPromise 캘린더 날짜, 시간 선택 값 받아오기
  src/pages/juniorPromise/components/BottomBar.tsx
  src/pages/juniorPromise/components/CalendarBottomSheet.tsx
  src/pages/juniorPromise/components/CustomCalendar.tsx
  src/pages/juniorPromise/components/EachTimeButton.tsx
  src/pages/juniorPromise/components/GrayLine.tsx
  src/pages/juniorPromise/components/SelectJuniorPromiseSection.tsx
  src/pages/juniorPromise/components/TimeList.tsx
  src/pages/juniorPromise/components/TimeSelectionButton.tsx
  src/pages/juniorPromise/constants/constants.ts
  src/pages/juniorPromise/utils/.gitkeep
  src/pages/juniorPromise/utils/formatBtnDateToString.ts
  src/pages/juniorPromise/utils/formatCalDateToString.ts
Labels: 지은, size/l

#70 [ Design ] Onboarding 공통 SelectBox 구현
  src/assets/svgs/ic_dropdown.svg
  src/assets/svgs/index.tsx
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/onboarding/components/SelectBox.tsx
  src/pages/onboarding/components/seniorOnboarding/Step재직기간.tsx
  src/pages/onboarding/constants.ts
Labels: ✨ Feat, 💄 Design, 숭, size/m

#85 [ Feat ] JuniorPromise 후배 약속 신청 모달 구현
  src/assets/svgs/ic_modal_check.svg
  src/assets/svgs/index.tsx
  src/pages/juniorPromise/components/CheckModal.tsx
  src/pages/juniorPromise/components/CheckModalContent.tsx
Labels: ✨ Feat, 지은, size/m

#98 [ Feat ] 선배 약속 수락, 거절 / 확정대기,예정약속,지난약속 선,후배 상세페이지 연결
  src/Router.tsx
  src/assets/svgs/bottom-sheet-Rectangle.svg
  src/assets/svgs/ic_arrow_down_mg.svg
  src/assets/svgs/img_empty.svg
  src/assets/svgs/img_sbhbhome_profile1.svg
  src/assets/svgs/img_sbhbhome_profile2.svg
  src/assets/svgs/index.tsx
  src/components/commons/BottomSheet.tsx
  src/components/commons/FullButton.tsx
  src/components/commons/modal/AutoCloseModal.tsx
  src/hooks/.gitkeep
  src/hooks/useCountDown.ts
  src/pages/juniorPromise/constants/.gitkeep
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
  src/pages/promiseDetail/components/Content.tsx
  src/pages/promiseDetail/components/PersonalTopic.tsx
  src/pages/promiseDetail/constants/constant.ts
  src/pages/promiseDetail/utils/formatDate.ts
  src/pages/promiseList/PromiseListPage.tsx
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/promiseList/components/PromiseTap.tsx
  src/pages/promiseList/components/PromiseTimerBtn.tsx
  src/pages/promiseList/components/RecentCard.tsx
  src/pages/promiseList/constants/constants.tsx
Labels: ✨ Feat, 서진

#99 [ Feat ] 개인정보 입력 뷰 기능 구현
  src/assets/images/img_start_profile1.png
  src/assets/images/img_start_profile2.png
  src/assets/images/index.tsx
  src/pages/onboarding/components/TextBox.tsx
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
Labels: ✨ Feat, 숭, size/m

#102 [Design] 선배 탐색 플로우 바텀시트 내 계열 content 생성
  .eslintrc.json
  src/components/commons/ToggleButton.tsx
  src/main.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/BottomSheetBg.tsx
  src/pages/juniorPromise/components/FieldList.tsx
  src/pages/juniorPromise/components/FilterButton.tsx
  src/pages/juniorPromise/components/PositionList.tsx
  src/pages/juniorPromise/components/SeniorListBackground.tsx
  src/pages/juniorPromise/constants/fieldList.ts
  src/pages/juniorPromise/constants/positionList.ts
Labels: ✨ Feat, 예림, size/xl

#86 [ Design ] 선/후배 약속 페이지 퍼블리싱
  src/App.tsx
  src/Router.tsx
  src/assets/svgs/bottom-sheet-Rectangle.svg
  src/assets/svgs/ic_cardarrow_right_gray.svg
  src/assets/svgs/ic_clock.svg
  src/assets/svgs/img_empty.svg
  src/assets/svgs/img_sbhbhome_profile1.svg
  src/assets/svgs/img_sbhbhome_profile2.svg
  src/assets/svgs/index.tsx
  src/components/commons/BottomSheet.tsx
  src/components/commons/FullButton.tsx
  src/components/commons/Nav.tsx
  src/components/commons/modal/AutoCloseModal.tsx
  src/components/commons/seniorCard/SeniorCard.tsx
  src/components/commons/seniorCard/utils/getLevelName.tsx
  src/hooks/.gitkeep
  src/hooks/useCountDown.ts
  src/main.tsx
  src/pages/juniorPromise/constants/.gitkeep
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
  src/pages/promiseDetail/components/Content.tsx
  src/pages/promiseDetail/components/PersonalTopic.tsx
  src/pages/promiseDetail/constants/constant.ts
  src/pages/promiseDetail/utils/formatDate.ts
  src/pages/promiseList/PromiseListPage.tsx
  src/pages/promiseList/commons/Layout.tsx
  src/pages/promiseList/commons/PromiseTap.tsx
  src/pages/promiseList/components/ProfileChip.tsx
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/promiseList/components/PromiseTap.tsx
  src/pages/promiseList/components/PromiseTimerBtn.tsx
  src/pages/promiseList/components/RecentCard.tsx
  src/pages/promiseList/components/SeniorJobChip.tsx
  src/pages/promiseList/components/Title.tsx
  src/pages/promiseList/constants/constants.tsx
  src/pages/promiseList/types/type.ts
  src/pages/promiseList/utils/calculateTimeLeft.ts
  src/pages/promiseList/utils/extractMonthAndDay.ts
  src/pages/promiseList/utils/generateChipColor.ts
  src/pages/promiseList/utils/getEmptyMessage.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/utils/getLevelName.tsx
Labels: ✨ Feat, 서진, size/xl

#96 [ Feat ] 약관동의 페이지 링크 연결 및 기능 구현
  .eslintrc.json
  src/assets/svgs/ic_arrow_right.svg
  src/assets/svgs/index.tsx
  src/pages/onboarding/components/commonOnboarding/Step약관동의.tsx
  src/pages/onboarding/constants.ts
  tsconfig.app.json
Labels: ✨ Feat, 숭, size/m

#105 [ Feat ] 타이머 기능 추가
  src/pages/onboarding/components/TextBox.tsx
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/utils/formatTime.ts
Labels: ✨ Feat, 지은, size/m

#107 [ Feat ] 졸업증명서 인증 구현
  src/pages/onboarding/components/TextBox.tsx
  src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx
  src/pages/onboarding/components/seniorOnboarding/Step졸업인증.tsx
Labels: 숭, size/m

#108 [ Feat ] CTA 관련 조건부 렌더링
  src/components/commons/FullButton.tsx
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/onboarding/components/Layout.tsx
  src/pages/onboarding/components/SelectBox.tsx
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step계열선택.tsx
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step약관동의.tsx
  src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx
  src/pages/onboarding/components/commonOnboarding/Step학교선택.tsx
  src/pages/onboarding/components/seniorOnboarding/Step명함인증.tsx
  src/pages/onboarding/components/seniorOnboarding/Step인증완료.tsx
  src/pages/onboarding/components/seniorOnboarding/Step재직기간.tsx
  src/pages/onboarding/components/seniorOnboarding/Step재직인증.tsx
  src/pages/onboarding/components/seniorOnboarding/Step졸업인증.tsx
  src/pages/onboarding/components/seniorOnboarding/Step직무선택.tsx
Labels: ✨ Feat, 숭, size/l

#115 [ Fix ] 학과 검색 뷰 고도화
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx
  src/pages/onboarding/components/seniorOnboarding/Step졸업인증.tsx
  src/pages/onboarding/constants.ts
Labels: ✨ Feat, 🛠 Fix, 숭, size/s

#93 [ Desgin ] juniorPromise 후배 약속 신청 페이지 세부 디자인, 레이아웃 조정
  src/pages/juniorPromise/components/Banner.tsx
  src/pages/juniorPromise/components/BottomBar.tsx
  src/pages/juniorPromise/components/CalendarBottomBar.tsx
  src/pages/juniorPromise/components/CalendarBottomSheet.tsx
  src/pages/juniorPromise/components/CustomCalendar.tsx
  src/pages/juniorPromise/components/EachTimeButton.tsx
  src/pages/juniorPromise/components/FilterButton.tsx
  src/pages/juniorPromise/components/SelectJuniorPromiseSection.tsx
  src/pages/juniorPromise/components/SelectJuniorWorryButton.tsx
  src/pages/juniorPromise/components/SelectJuniorWorryTextareaWrapper.tsx
  src/pages/juniorPromise/components/TimeList.tsx
  src/pages/juniorPromise/components/TimeSelectionButton.tsx
  src/pages/juniorPromise/constants/constants.ts
Labels: ✨ Feat, 지은, size/l

#123 [ Fix ] Nav 바 수정
  src/assets/svgs/ic_navi_look_black.svg
  src/assets/svgs/ic_navi_my_black.svg
  src/assets/svgs/ic_navi_promise_black.svg
  src/components/commons/Nav.tsx
Labels: 🛠 Fix, 지은, size/m

#114 [ Feat ] 선배프로필 필터링 버튼, 칩 기능 구현
  src/assets/svgs/img_hbhome_main.svg
  src/assets/svgs/index.tsx
  src/components/commons/Header.tsx
  src/components/commons/Nav.tsx
  src/components/commons/seniorCard/SeniorCard.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/BottomSheetBg.tsx
  src/pages/juniorPromise/components/FieldList.tsx
  src/pages/juniorPromise/components/FilterButton.tsx
  src/pages/juniorPromise/components/PositionList.tsx
  src/pages/juniorPromise/components/SeniorListBackground.tsx
  src/pages/juniorPromise/constants/fieldList.ts
  src/pages/juniorPromise/constants/positionList.ts
  src/pages/promiseList/PromiseListPage.tsx
  src/pages/promiseList/components/RecentCard.tsx
Labels: ✨ Feat, 예림, size/m

#124 [ Feat ] 닉네임 유효성 검증 API 연결
  src/pages/login/apis/loginAxios.ts
  src/pages/login/hooks/useLoginQuery.ts
  src/pages/onboarding/apis/nicknameAxios.ts
  src/pages/onboarding/components/TextBox.tsx
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
  src/pages/onboarding/hooks/useNicknameQuery.ts
  src/utils/apis/index.ts
Labels: ✨ Feat, 진, size/m

#135 [ Feat ] 후배플로우 연결 및 플로우
  src/Router.tsx
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/onboarding/components/Layout.tsx
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step계열선택.tsx
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step약관동의.tsx
  src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx
  src/pages/onboarding/components/commonOnboarding/Step학교선택.tsx
  src/pages/onboarding/components/juniorOnboarding/Step이메일입력.tsx
  src/pages/onboarding/components/seniorOnboarding/Step명함인증.tsx
  src/pages/onboarding/components/seniorOnboarding/Step인증완료.tsx
  src/pages/onboarding/components/seniorOnboarding/Step재직기간.tsx
  src/pages/onboarding/components/seniorOnboarding/Step졸업인증.tsx
  src/pages/onboarding/components/seniorOnboarding/Step직무선택.tsx
Labels: ✨ Feat, 숭, size/l

#143 [ Feat ] 휴대전화 인증 API 연결 및 조건부 렌더링 모달 구현
  src/assets/svgs/img_warning.svg
  src/assets/svgs/index.tsx
  src/components/commons/modal/BtnModal.tsx
  src/pages/onboarding/apis/phoneAxios.ts
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/hooks/usePhoneQuery.ts
Labels: ✨ Feat, 진, size/m

#139 [ Feat ] 실시간 검색 기능 구현
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/onboarding/apis/searchAxios.ts
  src/pages/onboarding/components/SearchBox.tsx
  src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx
  src/pages/onboarding/components/commonOnboarding/Step학교선택.tsx
  src/pages/onboarding/constants.ts
  src/pages/onboarding/hooks/useSearchDeptQuery.ts
  src/pages/onboarding/hooks/useSearchUnivQuery.ts
  src/pages/onboarding/type.ts
Labels: ✨ Feat, 숭, size/m

#141 [ Design ] JuniorPromise 후배 약속 플로우 연결
  src/assets/svgs/img_flag.svg
  src/assets/svgs/img_hbpromise.svg
  src/assets/svgs/img_medal.svg
  src/assets/svgs/img_promise_complete.svg
  src/assets/svgs/img_sbdetail_1.svg
  src/assets/svgs/img_sbdetail_2.svg
  src/assets/svgs/index.tsx
  src/components/commons/FullButton.tsx
  src/components/commons/modal/BtnModal.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/Banner.tsx
  src/pages/juniorPromise/components/CalendarBottomSheet.tsx
  src/pages/juniorPromise/components/GrayLine.tsx
  src/pages/juniorPromise/components/JuniorPromiseComplete.tsx
  src/pages/juniorPromise/components/SelectJuniorPromiseSection.tsx
  src/pages/juniorPromise/components/SelectJuniorWorryTitleWrapper.tsx
  src/pages/juniorPromise/components/TimeSelectionButton.tsx
  src/pages/juniorPromise/components/TimeSelectionTitleWrapper.tsx
  src/pages/promiseDetail/PromiseDetailPage.tsx
Labels: ✨ Feat, 지은, size/l

#154 [ Fix ] UX라이팅 수정사항 반영
  src/assets/images/img_namecard.png
  src/assets/images/img_success.png
  src/assets/images/index.tsx
  src/pages/onboarding/components/SelectBox.tsx
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/components/juniorOnboarding/Step이메일입력.tsx
  src/pages/onboarding/components/seniorOnboarding/Step명함인증.tsx
  src/pages/onboarding/components/seniorOnboarding/Step재직기간.tsx
  src/pages/onboarding/components/seniorOnboarding/Step졸업인증.tsx
  src/pages/onboarding/components/seniorOnboarding/Step직무선택.tsx
Labels: size/m

#146 [ Feat ] 구글밋 링크 생성 POST, 선배 약속 수락 PATCH
  src/components/commons/modal/AutoCloseModal.tsx
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseList/apis/patchSeniorPromiseAccept.ts
  src/pages/promiseList/apis/postGoogleMeetLink.ts
  src/pages/promiseList/hooks/queries.ts
  src/utils/apis/clients.ts
  src/utils/apis/index.ts
Labels: ✨ Feat, 서진, size/m

#147 [ Feat ] 선배 약속 거절 PATCH , 구글밋 링크 GET
  src/components/commons/BottomSheet.tsx
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseDetail/apis/patchSeniorPromiseAccept.ts
  src/pages/promiseDetail/apis/patchSeniorReject.ts
  src/pages/promiseDetail/apis/postGoogleMeetLink.ts
  src/pages/promiseDetail/constants/constant.ts
  src/pages/promiseDetail/hooks/queries.ts
  src/pages/promiseList/apis/getGoogleMeetLink.ts
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/promiseList/components/PromiseTimerBtn.tsx
  src/pages/promiseList/components/RecentCard.tsx
  src/pages/promiseList/hooks/queries.ts
Labels: ✨ Feat, 서진, size/m

#158 [ Feat ] 오늘의 선약, 확정 대기, 예정 약속, 지난 약속 조회
  src/assets/svgs/comingSoonModalImg.svg
  src/assets/svgs/ghost.svg
  src/assets/svgs/img_bfrelease.svg
  src/assets/svgs/index.tsx
  src/pages/promiseList/PromiseListPage.tsx
  src/pages/promiseList/apis/getPromiseList.ts
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/promiseList/components/PromiseTap.tsx
  src/pages/promiseList/hooks/queries.ts
  src/pages/promiseList/utils/extractMonthAndDay.ts
Labels: ✨ Feat, 서진, size/m

#162 [ Feat ] 약속 상세 페이지 조회 GET
  src/assets/svgs/img_headerlogo.svg
  src/assets/svgs/img_modal_accept.svg
  src/assets/svgs/img_modal_reject.svg
  src/assets/svgs/index.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
  src/pages/promiseDetail/apis/getPromiseDetail.ts
  src/pages/promiseDetail/hooks/queries.ts
  src/pages/promiseDetail/utils/formatDate.ts
  src/pages/promiseList/PromiseListPage.tsx
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/promiseList/utils/extractMonthAndDay.ts
Labels: ✨ Feat, 서진, size/m

#164 [ Feat ] 후배 약속신청 API 연결 (POST)
  src/App.tsx
  src/components/commons/modal/BtnModal.tsx
  src/pages/juniorPromise/apis/.gitkeep
  src/pages/juniorPromise/apis/postAppointment.ts
  src/pages/juniorPromise/components/JuniorPromiseComplete.tsx
  src/pages/juniorPromise/components/SelectJuniorPromiseSection.tsx
  src/pages/juniorPromise/components/SelectJuniorWorryButton.tsx
  src/pages/juniorPromise/components/SelectJuniorWorryTextareaWrapper.tsx
  src/pages/juniorPromise/hooks/queries.ts
Labels: ✨ Feat, 지은, size/m

#150 [ Feat ] 학교 이메일 인증 API 연결
  src/pages/onboarding/apis/univAxios.ts
  src/pages/onboarding/components/TextBox.tsx
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step학교선택.tsx
  src/pages/onboarding/components/juniorOnboarding/Step이메일입력.tsx
  src/pages/onboarding/constants.ts
  src/pages/onboarding/hooks/useUnivQuery.ts
Labels: ✨ Feat, 진, size/m

#156 [ Feat ] Onboarding 시작 페이지
  src/Router.tsx
  src/assets/svgs/ic_big_main_logo.svg
  src/assets/svgs/img_grad.svg
  src/assets/svgs/img_onboarding_hb.svg
  src/assets/svgs/img_onboarding_sb.svg
  src/assets/svgs/index.tsx
  src/pages/join/Button.tsx
  src/pages/join/JoinPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/login/SignupPage.tsx
Labels: ✨ Feat, 진

#173 [ Feat ] 에러페이지 구현
  src/Router.tsx
  src/pages/errorPage/ErrorPage.tsx
Labels: ✨ Feat, 진, size/m

#174 [ Fix ] Onboarding Build Error
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/components/juniorOnboarding/Step이메일입력.tsx
  src/pages/onboarding/components/seniorOnboarding/Step명함인증.tsx
  src/pages/onboarding/components/seniorOnboarding/Step재직인증.tsx
  src/pages/onboarding/components/seniorOnboarding/Step직무선택.tsx
  src/pages/onboarding/constants.ts
Labels: 🛠 Fix, 숭, size/m

#167 [ Feat ] 오늘의 선약, 확정 대기, 예정 약속, 지난 약속 조회 플로우 모두 연결
  src/assets/images/img_bfrelease.png
  src/assets/images/index.tsx
  src/assets/svgs/comingSoonModalImg.svg
  src/assets/svgs/ghost.svg
  src/assets/svgs/img_ghost.svg
  src/assets/svgs/index.tsx
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
  src/pages/promiseDetail/apis/patchSeniorReject.ts
  src/pages/promiseList/apis/getPromiseList.ts
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/promiseList/components/PromiseTap.tsx
  src/pages/promiseList/components/RecentCard.tsx
  src/pages/promiseList/hooks/queries.ts
  src/pages/seniorProfile/apis/seniorProfileAxios.ts
  src/pages/seniorProfile/components/Complete.tsx
  src/pages/seniorProfile/components/preView/index.tsx
Labels: ✨ Feat, 서진, size/m

#165 [ Feat ] 선배 선호 시간대 조회 API 연결 (GET)
  src/App.tsx
  src/components/commons/modal/BtnModal.tsx
  src/pages/juniorPromise/apis/getSeniorTimeAxios.ts
  src/pages/juniorPromise/components/CalendarBottomSheet.tsx
  src/pages/juniorPromise/components/CustomCalendar.tsx
  src/pages/juniorPromise/components/SelectJuniorPromiseSection.tsx
  src/pages/juniorPromise/components/TimeList.tsx
  src/pages/juniorPromise/hooks/queries.ts
  src/pages/juniorPromise/utils/changeFormat30Min.ts
  src/pages/juniorPromise/utils/getDay.ts
Labels: ✨ Feat, 지은, size/s

#179 [ Fix ] 약속 리스트 프로필 이미지 연결
  src/pages/promiseList/components/ProfileContainer.tsx
Labels: 🛠 Fix, 서진

#181 [ Fix ] 선배 선호 시간 조회 데이터 구조 반영
  src/App.tsx
  src/pages/juniorPromise/components/CalendarBottomSheet.tsx
  src/pages/juniorPromise/components/CustomCalendar.tsx
  src/pages/juniorPromise/utils/getSeniorValidWeekOfDay.ts
Labels: 🛠 Fix, 서진

#182 [ Feat ] seniorProfile PrewView 서진언니 쓸 수 있도록 variant 적용
  src/components/commons/seniorCard/SeniorCard.tsx
  src/pages/juniorPromise/apis/getSeniorTimeAxios.ts
  src/pages/juniorPromise/utils/getSeniorValidWeekOfDay.ts
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/seniorProfile/SeniorProfilePage.tsx
  src/pages/seniorProfile/apis/getSeniorProfileAxios.ts
  src/pages/seniorProfile/components/Example.tsx
  src/pages/seniorProfile/components/preView/Review.tsx
  src/pages/seniorProfile/components/preView/index.tsx
  src/pages/seniorProfile/hooks/useGetSeniorProfileQuery.ts
  src/pages/seniorProfile/hooks/useSeniorCardQuery.ts
  src/pages/seniorProfile/types.ts
  src/pages/seniorProfile/utils/weekToDay.ts
Labels: ✨ Feat, 진

#185 [ Feat ] seniorProfileExample step 구현
  src/pages/seniorProfile/components/Example.tsx
  src/pages/seniorProfile/components/preView/index.tsx
Labels: ✨ Feat, 진, size/m

#194 [ Fix ] 모달, 풀버튼, 헤더 가운데 정렬 적용
  src/components/commons/FullButton.tsx
  src/components/commons/Header.tsx
  src/components/commons/modal/AutoCloseModal.tsx
  src/pages/juniorPromise/components/BottomSheetBg.tsx
  src/pages/juniorPromise/components/SelectJuniorPromiseSection.tsx
  src/pages/promiseList/PromiseListPage.tsx
  src/pages/promiseList/components/ProfileChip.tsx
  src/pages/promiseList/components/RecentCard.tsx
Labels: 🛠 Fix, 서진, size/s

#195 [ Feat ] 선배 약속 신청 플로우 최종 연결 완료
  src/components/commons/SeniorCard.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/apis/getSeniorProfile.ts
  src/pages/juniorPromise/apis/postAppointment.ts
  src/pages/juniorPromise/components/CalendarBottomSheet.tsx
  src/pages/juniorPromise/components/CustomCalendar.tsx
  src/pages/juniorPromise/components/JuniorPromiseComplete.tsx
  src/pages/juniorPromise/components/SelectJuniorPromiseSection.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/promiseList/types/type.ts
  src/pages/seniorProfile/components/preView/index.tsx
Labels: ✨ Feat, 서진

#176 [ Feat ] ROLE LocalStorage 저장
  src/pages/join/Button.tsx
  src/pages/join/JoinPage.tsx
  src/pages/login/SignupPage.tsx
  src/pages/login/hooks/useLoginQuery.ts
  src/pages/onboarding/apis/joinAxios.ts
  src/pages/onboarding/components/Layout.tsx
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step계열선택.tsx
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step약관동의.tsx
  src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx
  src/pages/onboarding/components/commonOnboarding/Step학교선택.tsx
  src/pages/onboarding/components/juniorOnboarding/Step이메일입력.tsx
  src/pages/onboarding/components/seniorOnboarding/Step명함인증.tsx
  src/pages/onboarding/components/seniorOnboarding/Step재직기간.tsx
  src/pages/onboarding/components/seniorOnboarding/Step직무선택.tsx
  src/pages/onboarding/hooks/useJoinQuery.ts
  src/pages/onboarding/type.ts
Labels: ✨ Feat, 진, size/l

#192 [ Fix ] Navigate 오류 해결
  src/pages/onboarding/components/Layout.tsx
Labels: 🛠 Fix, 숭, size/xs

#144 [ fix ] 바텀시트 올라왔을때 바깥영역 스크롤 방지
  src/pages/juniorPromise/JuniorPromisePage.tsx
Labels: 🐛 bug, 예림, size/xs

#193 [ fix ] SeniorCard 레이아웃 조정
  src/components/commons/seniorCard/SeniorCard.tsx
  src/pages/seniorProfile/components/Example.tsx
Labels: 🛠 Fix, 예림, size/m

#190 [ Feat ] 온보딩 상태 통합 및 회원가입 API 연결
  src/Router.tsx
  src/assets/images/img_profile_complete.png
  src/assets/images/index.tsx
  src/pages/onboarding/apis/joinAxios.ts
  src/pages/onboarding/components/Layout.tsx
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step계열선택.tsx
  src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx
  src/pages/onboarding/components/commonOnboarding/Step약관동의.tsx
  src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx
  src/pages/onboarding/components/commonOnboarding/Step학교선택.tsx
  src/pages/onboarding/components/juniorOnboarding/StepComplete.tsx
  src/pages/onboarding/components/juniorOnboarding/Step이메일입력.tsx
  src/pages/onboarding/components/seniorOnboarding/Step재직기간.tsx
  src/pages/onboarding/components/seniorOnboarding/Step재직인증.tsx
  src/pages/onboarding/components/seniorOnboarding/Step직무선택.tsx
  src/pages/onboarding/constants.ts
  src/pages/onboarding/hooks/useJoinQuery.ts
  src/pages/onboarding/type.ts
Labels: size/l

#203 [ feat ] 프로필 이미지 등록 API 연결
  src/pages/onboarding/apis/profileImgAxios.ts
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
  src/pages/onboarding/hooks/useProfileImgQuery.tsx
Labels: ✨ Feat, 예림, size/s

#205 [ Feat ] 명함인증 API 연결
  src/pages/onboarding/apis/businesscardAxios.ts
  src/pages/onboarding/components/seniorOnboarding/Step명함인증.tsx
  src/pages/onboarding/hooks/useBusinessCardQuery.ts
Labels: ✨ Feat, 지은

#207 [ Feat ] 파비콘, OG태그 구현
  index.html
  public/OG.jpeg
  public/favicon.svg
Labels: ✨ Feat, 예림, size/s

#208 [ Fix ] 깨진 레이아웃 조정
  src/components/commons/FullButton.tsx
  src/components/commons/Loading.tsx
  src/components/commons/modal/BtnModal.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/onboarding/components/seniorOnboarding/Step명함인증.tsx
Labels: 🛠 Fix, 지은, size/s
