Repository TEAM-SEONYAK/SEONYAK_CLIENT, pull requests merged in 2024-09, with the labels that each got.

#216 [ Refactor ] 프롭스 줄이기, 필터 선택시 깜빡임 제거, 주석 제거
  src/hooks/seniorProfileQueries.ts
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/FilterButton.tsx
  src/pages/juniorPromise/components/SeniorListBackground.tsx
Labels: ♻️ Refactor, 예림, size/m

#233 [ Fix ] 라우팅 재설정
  src/Router.tsx
  src/components/commons/Nav.tsx
  src/pages/errorPage/ErrorPage.tsx
  src/pages/juniorPromise/components/promiseRequest/PromiseRequestPage.tsx
  src/pages/juniorPromise/components/promiseRequest/RequestComplete.tsx
  src/pages/login/hooks/useGoogleLoginMutation.ts
  src/pages/promiseDetail/PromiseDetailPage.tsx
  src/pages/promiseDetail/PromiseDetailPageJunior.tsx
  src/pages/seniorProfile/components/Complete.tsx
Labels: 🛠 Fix, 진, size/s

#236 [ Fix ] 구글 이모지 깨짐 개선
  src/assets/svgs/googleLogoIc.svg
Labels: 🛠 Fix, 진, size/s

#225 [ Fix ] self QA - 뒤로가기 버튼 수정, 약속신청 모달 위치 조정, 이미 있는 약속 신청시 alert
  src/pages/juniorPromiseRequest/JuniorPromiseRequestPage.tsx
  src/pages/juniorPromiseRequest/components/CheckModal.tsx
  src/pages/juniorPromiseRequest/hooks/queries.ts
Labels: 🛠 Fix, 지은, size/m

#240 [ Fix ] 학교검색 바텀시트 위치조정
  src/pages/onboarding/components/FullBottomSheet.tsx
Labels: 🛠 Fix, 진, size/xs

#235 [Fix] 바텀시트 내부 버튼 폭 수정 및 컨텐츠 간격 조정
  src/components/commons/ToggleButton.tsx
  src/pages/juniorPromise/components/BottomSheetBg.tsx
Labels: 🛠 Fix, 예림, size/s

#239 [ Fix ] 반응형 가운데 정렬
  src/components/commons/Loading.tsx
  src/components/commons/Toaster.tsx
  src/components/commons/ToggleButton.tsx
  src/pages/seniorProfile/components/TimeSelect/TimeAlldays.tsx
  src/pages/seniorProfile/components/TimeSelect/TimeWeekdays.tsx
  src/pages/seniorProfile/components/TimeSelect/index.tsx
  src/pages/seniorProfile/components/common/DropDown.tsx
  src/pages/seniorProfile/components/common/DurationSelect.tsx
Labels: 🛠 Fix, 진, size/m

#221 [ Refactor ] JuniorPromiseRequest 라우팅 분리
  src/Router.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/promiseRequest/CheckModal.tsx
  src/pages/juniorPromise/hooks/queries.ts
  src/pages/juniorPromiseRequest/JuniorPromiseRequestPage.tsx
  src/pages/juniorPromiseRequest/apis/getSeniorTimeAxios.ts
  src/pages/juniorPromiseRequest/apis/postAppointment.ts
  src/pages/juniorPromiseRequest/components/Banner.tsx
  src/pages/juniorPromiseRequest/components/CalendarBottomBar.tsx
  src/pages/juniorPromiseRequest/components/CalendarBottomSheet.tsx
  src/pages/juniorPromiseRequest/components/CheckModalContent.tsx
  src/pages/juniorPromiseRequest/components/CustomCalendar.tsx
  src/pages/juniorPromiseRequest/components/RequestComplete.tsx
  src/pages/juniorPromiseRequest/components/ScheduleSelect.tsx
  src/pages/juniorPromiseRequest/components/TimeList.tsx
  src/pages/juniorPromiseRequest/components/TimeListBtns.tsx
  src/pages/juniorPromiseRequest/components/WorryButtons.tsx
  src/pages/juniorPromiseRequest/components/WorryTextarea.tsx
  src/pages/juniorPromiseRequest/constants/constants.ts
  src/pages/juniorPromiseRequest/hooks/queries.ts
  src/pages/juniorPromiseRequest/types/.gitkeep
  src/pages/juniorPromiseRequest/utils/changeFormat30Min.ts
  src/pages/juniorPromiseRequest/utils/formatBtnDateToString.ts
  src/pages/juniorPromiseRequest/utils/formatCalDateToString.ts
  src/pages/juniorPromiseRequest/utils/getDay.ts
  src/pages/juniorPromiseRequest/utils/getSeniorValidWeekOfDay.ts
  src/pages/juniorPromiseRequest/utils/getTomorrow.ts
  src/pages/promiseList/components/ProfileContainer.tsx
  src/pages/seniorProfile/components/preView/index.tsx
Labels: ♻️ Refactor, 지은, size/l

#242 [ Refactor ] 컴포넌트 계층구조 변화 및 바텀시트 내부 칩 관리하는 상태 단일화
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/BottomSheet.tsx
  src/pages/juniorPromise/components/FieldList.tsx
  src/pages/juniorPromise/components/FilterButton.tsx
  src/pages/juniorPromise/components/PositionList.tsx
  src/pages/juniorPromise/components/SeniorSearch.tsx
  src/pages/juniorPromise/components/seniorFilter/Banner.tsx
Labels: ♻️ Refactor, 예림, size/l
