Repository TEAM-SEONYAK/SEONYAK_CLIENT, pull requests merged in 2024-08, with the labels that each got.

#217 [ Refactor ] 폴더 분리, 변수명 읽기 쉽게 변경, UI 조정
  src/components/commons/TitleBox.tsx
  src/pages/juniorPromise/JuniorPromisePage.tsx
  src/pages/juniorPromise/components/SelectJuniorWorryTitleWrapper.tsx
  src/pages/juniorPromise/components/TimeSelectionTitleWrapper.tsx
  src/pages/juniorPromise/components/promiseRequest/Banner.tsx
  src/pages/juniorPromise/components/promiseRequest/CalendarBottomBar.tsx
  src/pages/juniorPromise/components/promiseRequest/CalendarBottomSheet.tsx
  src/pages/juniorPromise/components/promiseRequest/CheckModal.tsx
  src/pages/juniorPromise/components/promiseRequest/CheckModalContent.tsx
  src/pages/juniorPromise/components/promiseRequest/CustomCalendar.tsx
  src/pages/juniorPromise/components/promiseRequest/PromiseRequestPage.tsx
  src/pages/juniorPromise/components/promiseRequest/RequestComplete.tsx
  src/pages/juniorPromise/components/promiseRequest/ScheduleSelect.tsx
  src/pages/juniorPromise/components/promiseRequest/TimeList.tsx
  src/pages/juniorPromise/components/promiseRequest/TimeListBtns.tsx
  src/pages/juniorPromise/components/promiseRequest/WorryButtons.tsx
  src/pages/juniorPromise/components/promiseRequest/WorryTextarea.tsx
  src/pages/juniorPromise/constants/constants.ts
Labels: ♻️ Refactor, 지은, size/l

#220 [ design ] 후배 약속 리스트 - 텅 뷰 가운데 정렬
  src/pages/promiseList/components/RecentCard.tsx
Labels: 💄 Design, 서진, size/xs

#226 [Feat] Presigned URL를 활용한 프로필 이미지 등록 구현
  src/pages/onboarding/apis/joinAxios.ts
  src/pages/onboarding/apis/profileImageAxios.ts
  src/pages/onboarding/apis/profileImgAxios.ts
  src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx
  src/pages/onboarding/hooks/usePresignedUrl.ts
  src/pages/onboarding/hooks/useProfileImgQuery.tsx
  src/pages/onboarding/type.ts
Labels: size/m
